import { describe, expect, it } from 'vitest';
import { installBackupFeature } from '../../src/features/backup/backupFeature.js';
import { installCalendarFeature } from '../../src/features/calendar/calendarFeature.js';
import { installCustomersFeature } from '../../src/features/customers/customersFeature.js';
import { installPartsFeature } from '../../src/features/parts/partsFeature.js';
import { installAbsenceFeature } from '../../src/features/absence/absenceFeature.js';
import { installDashboardFeature } from '../../src/features/dashboard/dashboardFeature.js';
import { installFormHelpersFeature } from '../../src/features/formHelpers/formHelpersFeature.js';
import { installKiPlanningFeature } from '../../src/features/kiPlanning/kiPlanningFeature.js';
import { installReplacementCarsFeature } from '../../src/features/replacementCars/replacementCarsFeature.js';
import { installSearchFeature } from '../../src/features/search/searchFeature.js';
import { installSettingsKiFeature } from '../../src/features/settings/settingsKiFeature.js';
import { installShiftTemplatesFeature } from '../../src/features/shiftTemplates/shiftTemplatesFeature.js';
import { installStaffFeature } from '../../src/features/staff/staffFeature.js';
import { installTabletFeature } from '../../src/features/tablet/tabletFeature.js';
import { installTerminDetailsActionsFeature } from '../../src/features/termine/terminDetailsActionsFeature.js';
import { installTerminFormActionsFeature } from '../../src/features/termine/terminFormActionsFeature.js';
import { installTimelineFeature } from '../../src/features/timeline/timelineFeature.js';
import { installTimeTrackingFeature } from '../../src/features/timeTracking/timeTrackingFeature.js';
import { installTodayFeature } from '../../src/features/today/todayFeature.js';
import { installWaitingActionsFeature } from '../../src/features/waitingActions/waitingActionsFeature.js';
import { installWorkTimeModalFeature } from '../../src/features/workTimeModal/workTimeModalFeature.js';
import { installWorkSchedulesFeature } from '../../src/features/workSchedules/workSchedulesFeature.js';

describe('feature installers', () => {
  it('registers extracted feature methods', () => {
    class TestApp {}

    installAbsenceFeature(TestApp);
    installBackupFeature(TestApp);
    installCalendarFeature(TestApp);
    installCustomersFeature(TestApp);
    installPartsFeature(TestApp);
    installDashboardFeature(TestApp);
    installFormHelpersFeature(TestApp);
    installKiPlanningFeature(TestApp);
    installReplacementCarsFeature(TestApp);
    installSearchFeature(TestApp);
    installSettingsKiFeature(TestApp);
    installShiftTemplatesFeature(TestApp);
    installStaffFeature(TestApp);
    installTabletFeature(TestApp);
    installTerminDetailsActionsFeature(TestApp);
    installTerminFormActionsFeature(TestApp);
    installTimelineFeature(TestApp);
    installTimeTrackingFeature(TestApp);
    installTodayFeature(TestApp);
    installWaitingActionsFeature(TestApp);
    installWorkTimeModalFeature(TestApp);
    installWorkSchedulesFeature(TestApp);

    expect(TestApp.prototype.loadAbwesenheit).toBeTypeOf('function');
    expect(TestApp.prototype.handleAbwesenheitSubmit).toBeTypeOf('function');
    expect(TestApp.prototype.loadBackupStatus).toBeTypeOf('function');
    expect(TestApp.prototype.handleCreateBackup).toBeTypeOf('function');
    expect(TestApp.prototype.loadKalender).toBeTypeOf('function');
    expect(TestApp.prototype.loadKalenderTag).toBeTypeOf('function');
    expect(TestApp.prototype.loadKalenderWoche).toBeTypeOf('function');
    expect(TestApp.prototype.openKalenderNeuerTerminModal).toBeTypeOf('function');
    expect(TestApp.prototype.handleKalenderTerminSubmit).toBeTypeOf('function');
    expect(TestApp.prototype.handleNaechsterSlot).toBeTypeOf('function');
    expect(TestApp.prototype.loadKunden).toBeTypeOf('function');
    expect(TestApp.prototype.openFahrzeugVerwaltung).toBeTypeOf('function');
    expect(TestApp.prototype.loadTeileStatusUebersicht).toBeTypeOf('function');
    expect(TestApp.prototype.renderTeileStatusTable).toBeTypeOf('function');
    expect(TestApp.prototype.setupTeileBestellenEventListeners).toBeTypeOf('function');
    expect(TestApp.prototype.loadTeileBestellungen).toBeTypeOf('function');
    expect(TestApp.prototype.teileAlsBestellt).toBeTypeOf('function');
    expect(TestApp.prototype.teileStatusAufLoesen).toBeTypeOf('function');
    expect(TestApp.prototype.arbeitenTeileStatusAufLoesen).toBeTypeOf('function');
    expect(TestApp.prototype.loadDashboard).toBeTypeOf('function');
    expect(TestApp.prototype.loadDashboardKPIs).toBeTypeOf('function');
    expect(TestApp.prototype.handleArbeitAutocomplete).toBeTypeOf('function');
    expect(TestApp.prototype.showAutocomplete).toBeTypeOf('function');
    expect(TestApp.prototype.setupAuslastungKalender).toBeTypeOf('function');
    expect(TestApp.prototype.renderAuslastungKalender).toBeTypeOf('function');
    expect(TestApp.prototype.setupEditAuslastungKalender).toBeTypeOf('function');
    expect(TestApp.prototype.setupSchnellKalender).toBeTypeOf('function');
    expect(TestApp.prototype.requestKITagesplanung).toBeTypeOf('function');
    expect(TestApp.prototype.requestKIWochenplanung).toBeTypeOf('function');
    expect(TestApp.prototype.showKIPlanungModal).toBeTypeOf('function');
    expect(TestApp.prototype.displayKITagesvorschlag).toBeTypeOf('function');
    expect(TestApp.prototype.uebernehmeAlleKIVorschlaege).toBeTypeOf('function');
    expect(TestApp.prototype.calculateTageskapazitaetMinuten).toBeTypeOf('function');
    expect(TestApp.prototype.findeNaechstenVerfuegbarenTag).toBeTypeOf('function');
    expect(TestApp.prototype.loadErsatzautos).toBeTypeOf('function');
    expect(TestApp.prototype.renderErsatzautoListe).toBeTypeOf('function');
    expect(TestApp.prototype.handleNameSuche).toBeTypeOf('function');
    expect(TestApp.prototype.setupGlobaleSuche).toBeTypeOf('function');
    expect(TestApp.prototype.loadWerkstattSettings).toBeTypeOf('function');
    expect(TestApp.prototype.checkKIStatus).toBeTypeOf('function');
    expect(TestApp.prototype.loadSchichtTemplates).toBeTypeOf('function');
    expect(TestApp.prototype.handleSchichtTemplateSubmit).toBeTypeOf('function');
    expect(TestApp.prototype.loadMitarbeiter).toBeTypeOf('function');
    expect(TestApp.prototype.saveMitarbeiter).toBeTypeOf('function');
    expect(TestApp.prototype.loadTabletEinstellungen).toBeTypeOf('function');
    expect(TestApp.prototype.loadTermine).toBeTypeOf('function');
    expect(TestApp.prototype.showEinplanenDialog).toBeTypeOf('function');
    expect(TestApp.prototype.confirmEinplanenDatum).toBeTypeOf('function');
    expect(TestApp.prototype.openSplitModal).toBeTypeOf('function');
    expect(TestApp.prototype.executeSplit).toBeTypeOf('function');
    expect(TestApp.prototype.openErweiterungModal).toBeTypeOf('function');
    expect(TestApp.prototype.speichereErweiterung).toBeTypeOf('function');
    expect(TestApp.prototype.toggleAbholungDetails).toBeTypeOf('function');
    expect(TestApp.prototype.loadEditTermine).toBeTypeOf('function');
    expect(TestApp.prototype.fillEditTerminForm).toBeTypeOf('function');
    expect(TestApp.prototype.getPhasenFromForm).toBeTypeOf('function');
    expect(TestApp.prototype.showTerminVorschau).toBeTypeOf('function');
    expect(TestApp.prototype.executeTerminSave).toBeTypeOf('function');
    expect(TestApp.prototype.showSchnellStatusDialog).toBeTypeOf('function');
    expect(TestApp.prototype.speichereSchnellBearbeitung).toBeTypeOf('function');
    expect(TestApp.prototype.renderZeitleiste).toBeTypeOf('function');
    expect(TestApp.prototype.renderZeitleisteRow).toBeTypeOf('function');
    expect(TestApp.prototype.zeitleisteKontextSplit).toBeTypeOf('function');
    expect(TestApp.prototype.loadZeitstempelung).toBeTypeOf('function');
    expect(TestApp.prototype.navigateZeitverwaltung).toBeTypeOf('function');
    expect(TestApp.prototype.loadHeuteTermine).toBeTypeOf('function');
    expect(TestApp.prototype.renderHeuteTabelle).toBeTypeOf('function');
    expect(TestApp.prototype.setupWartendeAktionenKundensuche).toBeTypeOf('function');
    expect(TestApp.prototype.handleWartendeAktionSubmit).toBeTypeOf('function');
    expect(TestApp.prototype.loadWartendeAktionen).toBeTypeOf('function');
    expect(TestApp.prototype.wartendeAktionEinplanen).toBeTypeOf('function');
    expect(TestApp.prototype.wartendeAktionErledigt).toBeTypeOf('function');
    expect(TestApp.prototype.wartendeAktionLoeschen).toBeTypeOf('function');
    expect(TestApp.prototype.saveTeileStatus).toBeTypeOf('function');
    expect(TestApp.prototype.openArbeitszeitenModal).toBeTypeOf('function');
    expect(TestApp.prototype.loadModalPhasen).toBeTypeOf('function');
    expect(TestApp.prototype.openTagesUebersichtModal).toBeTypeOf('function');
    expect(TestApp.prototype.updateModalGesamtzeit).toBeTypeOf('function');
    expect(TestApp.prototype.renderModalTeileStatusSection).toBeTypeOf('function');
    expect(TestApp.prototype.saveArbeitszeitenModal).toBeTypeOf('function');
    expect(TestApp.prototype.loadArbeitszeitenForPerson).toBeTypeOf('function');
    expect(TestApp.prototype.saveWochenMuster).toBeTypeOf('function');
  });
});
